controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    gravity_compensation_example_controller:
      type: franka_example_controllers/GravityCompensationExampleController

    joint_impedance_example_controller:
      type: franka_example_controllers/JointImpedanceExampleController

    joint_velocity_example_controller:
      type: franka_example_controllers/JointVelocityExampleController

    joint_position_example_controller:
      type: franka_example_controllers/JointPositionExampleController

    cartesian_velocity_example_controller:
      type: franka_example_controllers/CartesianVelocityExampleController

    cartesian_pose_example_controller:
      type: franka_example_controllers/CartesianPoseExampleController

    cartesian_pose_elbow_example_controller:
      type: franka_example_controllers/CartesianElbowExampleController

    joint_impedance_with_ik_example_controller:
      type: franka_example_controllers/JointImpedanceWithIKExampleController

    cartesian_orientation_example_controller:
      type: franka_example_controllers/CartesianOrientationExampleController

    elbow_example_controller:
      type: franka_example_controllers/ElbowExampleController

    move_to_start_example_controller:
      type: franka_example_controllers/MoveToStartExampleController

    model_example_controller:
      type: franka_example_controllers/ModelExampleController

    gripper_example_controller:
      type: franka_example_controllers/GripperExampleController      

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    # More controller instances here
    # ...

cartesian_impedance_controller:
  ros__parameters:
    end_effector_link: "fr3_hand_tcp"
    robot_base_link: "fr3_link0"
    ft_sensor_ref_link: "fr3_hand_tcp"
    compliance_ref_link: "fr3_hand_tcp"
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7
      
    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity

    stiffness:
      trans_x: 500.0
      trans_y: 500.0
      trans_z: 500.0
      rot_x: 20.0
      rot_y: 20.0
      rot_z: 20.0

    nullspace_stiffness: 10.0
    compensate_gravity: false
    compensate_coriolis: true
    compensate_dJdq: false



motion_control_handle:
  ros__parameters:
    end_effector_link: "fr3_hand_tcp"
    robot_base_link: "fr3_link0"
    joints:
      - fr3_joint1
      - fr3_joint2
      - fr3_joint3
      - fr3_joint4
      - fr3_joint5
      - fr3_joint6
      - fr3_joint7

joint_impedance_with_ik_example_controller:
  ros__parameters:
    k_gains:
      - 600.0
      - 600.0
      - 600.0
      - 600.0
      - 250.0
      - 150.0
      - 50.0
    d_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 10.0
      - 10.0
      - 5.

joint_impedance_example_controller:
  ros__parameters:
    k_gains:
      - 24.0
      - 24.0
      - 24.0
      - 24.0
      - 10.0
      - 6.0
      - 2.0
    d_gains:
      - 2.0
      - 2.0
      - 2.0
      - 1.0
      - 1.0
      - 1.0
      - 0.5
move_to_start_example_controller:
  ros__parameters:
    k_gains:
      - 600.0
      - 600.0
      - 600.0
      - 600.0
      - 250.0
      - 150.0
      - 50.0
    d_gains:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 10.0
      - 10.0
      - 5.
