controller_manager:
  ros__parameters:
    thread_priority: 99
    update_rate: 1000  # Hz
  
    joint_position_controller_left:
      type: position_controllers/JointGroupPositionController

    joint_position_controller_right:
      type: position_controllers/JointGroupPositionController

    joint_velocity_controller_all:
      type: velocity_controllers/JointGroupVelocityController

    joint_velocity_controller_left:
      type: velocity_controllers/JointGroupVelocityController

    joint_velocity_controller_right:
      type: velocity_controllers/JointGroupVelocityController

    joint_effort_controller_left:
      type: effort_controllers/JointGroupEffortController
      
    joint_effort_controller_right:
      type: effort_controllers/JointGroupEffortController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_controller_left:
  ros__parameters:
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7

joint_position_controller_right:
  ros__parameters:
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7

joint_velocity_controller_all:
  ros__parameters:
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7

joint_velocity_controller_left:
  ros__parameters:
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7

joint_velocity_controller_right:
  ros__parameters:
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7

joint_effort_controller_left:
  ros__parameters:
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7
    joint_limits:
      has_velocity_limits: true
      max_velocity: 2.175

joint_effort_controller_right:
  ros__parameters:
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7
    joint_limits:
      has_velocity_limits: true
      max_velocity: 2.175