controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_position_controller_left:
      type: position_controllers/JointGroupPositionController

    joint_position_controller_right:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_position_controller_left:
  ros__parameters:
    joints:
      - franka2_fr3_joint1
      - franka2_fr3_joint2
      - franka2_fr3_joint3
      - franka2_fr3_joint4
      - franka2_fr3_joint5
      - franka2_fr3_joint6
      - franka2_fr3_joint7

joint_position_controller_right:
  ros__parameters:
    joints:
      - franka1_fr3_joint1
      - franka1_fr3_joint2
      - franka1_fr3_joint3
      - franka1_fr3_joint4
      - franka1_fr3_joint5
      - franka1_fr3_joint6
      - franka1_fr3_joint7
