controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    cartesian_compliance_controller:
      type: cartesian_compliance_controller/CartesianComplianceController
      
    cartesian_force_controller:
      type: cartesian_force_controller/CartesianForceController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle
      
    end_effector_controller:
      type: end_effector_controller/EndEffectorControl

    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    gravity_compensation:
      type: gravity_compensation/GravityCompensation
      
end_effector_controller:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "probe"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7

cartesian_impedance_controller:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "probe"
    compliance_ref_link: "probe"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7
      
    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity

    stiffness:
      trans_x: 1300.0
      trans_y: 1300.0
      trans_z: 1300.0
      rot_x: 70.0
      rot_y: 70.0
      rot_z: 70.0

    compensate_gravity: false 
    compensate_coriolis: false 
    command_current_configuration: false
    frame_topic_name: "/taget_frame"



motion_control_handle:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7

gravity_compensation:
  ros__parameters:
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7
    compensate_gravity: false
    compensate_coriolis: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "probe"
    compliance_ref_link: "probe"
