controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    franka_robot_state_broadcaster:
      type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster

    cartesian_compliance_controller:
      type: cartesian_compliance_controller/CartesianComplianceController
      
    cartesian_force_controller:
      type: cartesian_force_controller/CartesianForceController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle
      
    end_effector_controller:
      type: end_effector_controller/EndEffectorControl

    cartesian_impedance_controller:
      type: cartesian_impedance_controller/CartesianImpedanceController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    gravity_compensation:
      type: gravity_compensation/GravityCompensation

    cartesian_impedance_example_controller:
      type: franka_example_controllers/CartesianImpedanceExampleController
      
end_effector_controller:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "probe"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7

cartesian_impedance_controller:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "probe"
    compliance_ref_link: "probe"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7
      
    command_interfaces:
      - effort
    
    state_interfaces:
      - position
      - velocity

    stiffness:
      trans_x: 1000.0
      trans_y: 1000.0
      trans_z: 1000.0
      rot_x: 60.0
      rot_y: 60.0
      rot_z: 40.0

    force_control:
      # k_p: 1.0
      # k_d: 0.02
      # k_i: 1.5
      k_p: 1.0
      k_d: 0.0
      k_i: 3.0
      

    nullspace_desired_configuration: [0.0122955, 0.252305, -0.0402674, -2.14163, 0.0424824, 1.69748, 0.20905]
    
    nullspace_stiffness: 0.0

    compensate_gravity: false 
    compensate_coriolis: false 
    compensate_dJdq: false
    frame_topic_name: "/target_frame"



motion_control_handle:
  ros__parameters:
    end_effector_link: "probe"
    robot_base_link: "arm1_fr3_link0"
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7

gravity_compensation:
  ros__parameters:
    joints:
      - arm1_fr3_joint1
      - arm1_fr3_joint2
      - arm1_fr3_joint3
      - arm1_fr3_joint4
      - arm1_fr3_joint5
      - arm1_fr3_joint6
      - arm1_fr3_joint7
    compensate_gravity: false
    compensate_coriolis: false
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    end_effector_link: "arm1_fr3_link8"
    robot_base_link: "arm1_fr3_link0"
    ft_sensor_ref_link: "arm1_fr3_link8"
    compliance_ref_link: "arm1_fr3_link8"

cartesian_impedance_example_controller:
  ros__parameters:
    arm_id: "fr3"
    joint_prefix: "arm1_fr3"

