name: Web Page Build

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'staging'
  push:
    branches:
      - main
      - internshipper-bimanual

jobs:
  doxygen-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pages: write
      id-token: write
    
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Installs
        run: |
          sudo apt-get update
          sudo apt-get install -y git wget doxygen

      - name: Build docs
        run: doxygen doxyfile

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: docs
          retention-days: 90

  deploy:
    needs: doxygen-build

    permissions:
      contents: read
      pages: write
      id-token: write
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 